# Generated by Django 5.2.9 on 2025-12-12 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('evaluable', 'Evaluable'), ('no_evaluable', 'No evaluable')], max_length=15)),
                ('modalidad', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], max_length=15)),
                ('fecha_limite', models.DateField()),
                ('enunciado', models.TextField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='tareas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('finalizada', 'Finalizada'), ('validada', 'Validada'), ('no_validada', 'No validada')], default='pendiente', max_length=15)),
                ('fecha_entrega_alumno', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_profesor', models.TextField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tareas.tarea')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_realizadas', to='tareas.usuario')),
                ('profesor_validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_validadas', to='tareas.usuario')),
            ],
            options={
                'unique_together': {('tarea', 'alumno')},
            },
        ),
    ]
