# Generated by Django 5.2.8 on 2025-12-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='comentarios_profesor',
        ),
        migrations.RemoveField(
            model_name='tareaevaluable',
            name='puntuacion_maxima',
        ),
    ]
