# Generated by Django 5.2.8 on 2025-12-18 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('enunciado', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TareaEvaluable',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tareas.tarea')),
                ('requiere_validacion_profesor', models.BooleanField(default=True)),
                ('puntuacion_maxima', models.PositiveIntegerField(default=10)),
                ('validada', models.BooleanField(default=False)),
                ('validada_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tareas.tarea',),
        ),
        migrations.CreateModel(
            name='TareaGrupal',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tareas.tarea')),
                ('alumnos', models.ManyToManyField(limit_choices_to={'rol': 'alumno'}, related_name='tareas_grupales', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tareas.tarea',),
        ),
        migrations.CreateModel(
            name='TareaIndividual',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tareas.tarea')),
                ('alumno_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'alumno'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_individuales', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tareas.tarea',),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('validada', 'Validada'), ('no_validada', 'No validada')], default='pendiente', max_length=15)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_profesor', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('profesor_validador', models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_validadas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tareas.tarea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tarea', 'alumno'), name='entrega_unica_por_alumno')],
            },
        ),
    ]
